module.exports = {
  apps: [
    {
      name: 'debuta-backend',
      script: 'server.js',
      cwd: '/var/www/debuta/backend',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: '/var/log/debuta/error.log',
      out_file: '/var/log/debuta/out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
    },
    {
      name: 'debuta-apk',
      script: 'server.js',
      cwd: '/var/www/debuta/apk-server',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '128M',
      env_production: {
        NODE_ENV: 'production',
        PORT: 3030,
        BASE_URL: 'https://debuta.online/apk',
      },
      error_file: '/var/log/debuta/apk-error.log',
      out_file: '/var/log/debuta/apk-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
    },
  ],
};
